builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

    main: ./cmd/mainA
    id: mainA
    binary: mainA

  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

    main: ./cmd/mainB
    id: mainB
    binary: mainB
